[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'poe2-chat-notifier'
version = '1.0.0'

[project.scripts]
poe2-chat-notifier = 'poe2_chat_notifier.main:main'
